baseURL = "/~simmsb/"
languageCode = "en-uk"
title = "~simmsb"
theme = "hugo-classic"
preserveTaxonomyNames = true
pygmentsCodeFences = true
pygmentsStyle = "manni"

[output."blogdown::html_page"]
toc = true

[params]
description = "lancs/~simmsb"
footer = "[GitHub](https://github.com/nitros12) | [Blog Source](https://github.com/nitros12/blog_)"
rfooter = "This blog was written in [Emacs](https://www.gnu.org/software/emacs/)"
